# Repository settings, applied by the Probot "Settings" app.
# https://github.com/repository-settings/app

repository:
  name: tailscale-acls
  description: "regulad's Tailscale policy"
  topics: tailscale, tailnet, acl, gitops, hujson

  private: false

  has_issues: false
  has_projects: false
  has_wiki: false
  has_downloads: false
  has_discussions: false
  # pull requests disabled out-of-band

  default_branch: master
